---
- hosts: localhost
  gather_facts: true
  become: yes
  become_user: root
  vars:
    yum: { update_cache: false }
    auth_config: { ldap_host: 'ldap.corp.redhat.com', ldap_base: 'dc=redhat,dc=com', kerb_host: 'kerberos.corp.redhat.com', kerb_realm: 'REDHAT.COM' }
    sudoers_list:
      - { name: rpelisse }
      - { name: carlo }
      - { name: cdewolf }
      - { name: belaran }
      - { name: baranowb }
      - { name: dpospisi }
      - { name: dominik }
      - { name: egonzale }
      - { name: istudens }
      - { name: thofman }
      - { name: wangc }
      - { name: mstefank }
      - { name: iweiss }
      - { name: lgao}
    services_list:
      -
        name: jboss-eap7
        pidfile: /var/run/jboss-eap/jboss-eap.pid
        start_program: /etc/init.d/jboss-eap7
        stop_program: /etc/init.d/jboss-eap7
        bind_addr: "{{ ansible_nodename }}"
        port: 8480
        nb_restarts: 3
        checks:
          -
            context: /jenkins/login
            action: alert
            timeout: 6
          -
            context: /jenkins/login
            action: restart
            timeout: 6
          -
            context: /mjolnir
            action: alert
            timeout: 6
          -
            context: /prbz-overview
            action: alert
            timeout: 6
      - { name: "postgresql", pidfile: "/var/run/postmaster.5432.pid", start_program: "/etc/init.d/postgresql", stop_program: "/etc/init.d/postgresql" }
      -
        name: nginx
        pidfile: /var/run/nginx.pid
        start_program: /etc/init.d/nginx
        stop_program: /etc/init.d/nginx
        bind_addr: "{{ ansible_nodename }}"
        port: 443
        nb_restarts: 3
        protocol: HTTPS
        checks:
          -
            context: "/jenkins/login"
            action: alert
            timeout: 6
          -
            context: "/jenkins/login"
            action: restart
            timeout: 6
          -
            context: "/mjolnir"
            action: alert
            timeout: 6
          -
            context: "/prbz-overview"
            action: alert
            timeout: 6
      -
        name: "docker"
        pidfile: "/var/run/docker.pid"
        start_program: "/etc/init.d/docker"
        stop_program: "/etc/init.d/docker"
        bind_addr: 127.0.0.1
        port: 4243
        nb_restarts: 3
        checks:
          -
            context: /version
            action: alert
            timeout: 6
          - context: /version
            action: restart
            timeout: 6
      - { name: "tuned", pidfile: "/var/run/tuned/tuned.pid", start_program: "/etc/init.d/tuned", stop_program: "/etc/init.d/tuned" }
      - { name: "sssd", pidfile: "/var/run/sssd.pid", start_program: "/etc/init.d/sssd", stop_program: "/etc/init.d/sssd" }
      - { name: "oddjobd", pidfile: "/var/run/oddjobd.pid", start_program: "/etc/init.d/oddjobd", stop_program: "/etc/init.d/oddjobd" }
      - { name: "sshd", pidfile: "/var/run/sshd.pid", start_program: "/etc/init.d/sshd", stop_program: "/etc/init.d/sshd" }
      - { name: "jboss-set-ircbot", pidfile: "/var/run/jboss-set/jboss-set-ircbot.pid", start_program: "/etc/init.d/jboss-set-ircbot", stop_program: "/etc/init.d/jboss-set-ircbot" }
    tuned_profile_target : 'throughput-performance'
    devices_list:
      - { name: 'lo:10', filename: 'lo_10', ip_addr: 127.0.1.1,  netmask: 255.255.255.0, network: 127.0.0.0, broadcast: 127.255.255.255, onboot: 'yes' }
      - { name: 'lo:11', filename: 'lo_11', ip_addr: 127.0.1.2,  netmask: 255.255.255.0, network: 127.0.0.0, broadcast: 127.255.255.255, onboot: 'yes' }
    dnsnames:
      - { name: 'raw.githubusercontent.com' }
      - { name: 'kerberos.corp.redhat.com' }
      - { name: 'ldap.corp.redhat.com' }
      - { name: 'smtp.corp.redhat.com' }
      - { name: 'repository.jboss.org' }
      - { name: 'download.devel.redhat.com' }
      - { name: 'download-ipv4.eng.brq.redhat.com' }
      - { name: 'issues.jboss.org' }
      - { name: 'bugzilla.redhat.com' }
      - { name: 'central.maven.org' }
      - { name: 'repo1.maven.org' }
      - { name: 'repo1.maven.org' }
    kdump: { dump_level: '0'}
    docker: { suspiciously_long_running_time: '86395' }
    jboss: { bind_addr: "{{ ansible_nodename }}", port_shift: '400', home: '/opt/rh/eap7/root/usr/share/wildfly', jvm_memory: '2048m', package_name: 'eap7-wildfly', config: 'thunder.xml' }
    custom_monitoring_scripts:
      - { check_name: 'docker-check', script_name: 'check-docker-container', timeout: 5000 }
      - { check_name: 'eap7-check', script_name: 'check-eap7', timeout: 5000 }
      - { check_name: 'dead-jbossas', script_name: 'dead-jbossas', timeout: 5000 }
      - { check_name: 'sudo-group-check', script_name: 'sudo-group-check', timeout: 5000 }
      - { check_name: 'dns-check', script_name: 'dns-check', timeout: 5000 }
      - { check_name: 'docker-space-monitoring', script_name: 'docker-space-monitoring', timeout: 5000 }
    scripts_home: { path: '/opt/jboss-set-ci-scripts/ops' }
    disabled_services_list:
      - { name: 'libvirtd', reason: 'came with RHEV install, finally not used' }
      - { name: 'httpd', reason: 'came with RHEV installed and highly customized, so unused' }
      - { name: 'jenkins', reason: 'Jenkins is deployed on top of JBoss EAP, not run standalone' }
      - { name: 'nfs', reason: 'No reason to run NFS server, most likely leftover from RHEL setup' }
      - { name: 'rpcbind', reason: 'No reason to let the rpcbind sever running' }
      - { name: 'jbossas', reason: 'No longer used...' }
    yum_repositories_list:
      - { name: 'jboss-set'  }
    maven_http_cache_common_config: { name: 'maven_caches', directory: '/home/jboss/maven_central_cache', max_size: '20g', inactive: '90d', expires: '90d' }
    maven_http_caches:
        -  { name: 'maven_central', path: '/maven/', port: '80', protocol: 'HTTP', url: 'http://central.maven.org/maven2/' }
        -  { name: 'jb-eap-7.1-rhel-7-maven-build', path: '/eap-7.1/', port: '80', protocol: 'HTTP', url: 'http://download-node-02.eng.bos.redhat.com/brewroot/repos/jb-eap-7.1-rhel-7-maven-build/latest/maven/' }
        -  { name: 'jb-eap-7.0-rhel-7-maven-build', path: '/eap-7.0/', port: '80', protocol: 'HTTP', url: 'http://download-node-02.eng.bos.redhat.com/brewroot/repos/jb-eap-7.0-rhel-7-maven-build/latest/maven/' }
        -  { name: 'jboss.org', path: '/jboss/', port: '80', protocol: 'HTTP', url: 'http://repository.jboss.org/nexus/content/groups/public/' }
    remote_http_services:
        -  { name: 'github', path: '/jboss-set/' , hostname: 'github.com' }
    logs_cleaning:
      -  { name: 'cleaning-eap-server-logs',  root_folder: '/opt/rh/eap7/root/usr/share/wildfly/standalone/log', nb_days_oldest: 31, filename_pattern: 'server*.log.20*'}
  tasks:
    - name: " ******* STAGE 0 *******"
      debug: msg=" >>> Check Ansible Set Up <<<"

    - name: "Ensure ansible facts.d is created"
      file: path=/etc/ansible/facts.d/ state=directory

    - name: "Load secrets"
      include_vars: secrets.yml
      when: ansible_hostname == "thunder"

    - include_vars: dummy_secret.yml
      when: ansible_hostname != "thunder"

    - include: tasks/repos.yml

    - name: " ******* STAGE 1 *******"
      debug: msg=" >>> OS and Kernel Configuration and Optimization <<<"

    - include: tasks/kdump.yml
    - include: tasks/os-config.yml
    - include: tasks/sysctl.yml
    - include: tasks/tuned-adm.yml
    - include: tasks/selinux.yml

    - name: " ******* STAGE 2 *******"
      debug: msg=" >>> Authentification and Sudoers <<<"

    - include: tasks/authconfig.yml
    - include: tasks/sshd.yml
    - include: tasks/sudoers.yml

    - name: " ******* STAGE 3 *******"
      debug: msg=" >>> Set Up Required Infrastructure Services <<<"

    - include: tasks/disabled.yml
    - include: tasks/postgres.yml
    - include: tasks/docker.yml
    - include: tasks/nginx.yml

    - name: " ******* STAGE 4 *******"
      debug: msg=" >>> JBoss EAP and SET Webapps <<<"

    - include: tasks/jboss-set-ci-scripts.yml
    - include: tasks/pull-request-processor.yml

    - include: tasks/jboss-eap7.yml
    - include: tasks/mjolnir.yml
    - include: tasks/prbz-overview.yml
    - include: tasks/jenkins.yml

    - name: " ******* STAGE 5 *******"
      debug: msg=" >>> Monitoring and Cronjobs <<<"

    - include: tasks/cronjobs.yml
    - include: tasks/monit.yml
    - include: tasks/logrotate.yml

    - name: "******* STAGE 6 *******"
      debug: msg=" >>> Tools and misc <<<"

    - include: tasks/tools.yml
    - include: tasks/ircbot.yml

