---
- hosts: localhost
  gather_facts: no
  become: yes
  become_user: root
  vars_files:
      - vars/olympus.yml
      - vars/monit.yml
      - vars/caches.yml
      - vars/java_certs.yml
  roles:
     # stage 1 - OS settings and optimizations
    - selinux
    - motd
    - bashrc
    - kdump
    - sysctl
    - tuned
#    # stage 2 - main services
    - sshd
    - monit
    - nginx
    # stage 3 - auth and sudoers.yml
    # TODO
    #
    # stage 4 - java and jenkins
    - java_certs
    - jenkins
    - old_releases
      #  pre_tasks:
          #    - hostname:
          #name: "{{ ansible_hostname }}"
